name: "Deploy to AWS S3"
description: "hosting a static website on AWS"
inputs:
  bucket:
    description: "the S3 bucket name"
    required: true
  bucket-region: "us-east-1"
    description: "the region of the S3 bucket"
    required: false
    default: "us-east-1" # assumes this region as a default
  dist-folder:
    description: "the folder containing the deployable files"
    required: true
runs:
  using: 'node16'
  main: 'main.js'